apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec: 
      containers:
      - name: pythonapp
        image: huarami/pythonapp:v1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata: 
  name: service
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004 
